config/routes.rb
Rails.application.routes.draw do
  root "events#index"

  resources :events, only: [:index, :new, :show, :create]  do
    resources :attendee_events
  end

  resources :attendee_events,only: [:new]

  devise_for :users, controllers: {
    sessions: 'users/sessions'
    }
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/attendee_event.rb
class AttendeeEvent < ApplicationRecord
  self.primary_key = [:attendee_id,:attended_event_id]
  belongs_to :attendee, class_name: "User"
  belongs_to :attended_event, class_name: "Event"
end

app/models/event.rb
class Event < ApplicationRecord
  validates :location, presence: true, length: {minimum:6, maximum:20}
  validates :about, presence: true
  validates :title, presence: true
  validates :event_date, presence: true


  belongs_to :creator, class_name: "User"

  has_many :attendee_events, foreign_key: :attended_event_id
  has_many :attendees, through: :attendee_events, source: :attendee

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :created_events, class_name: "Event", foreign_key: "creator_id", inverse_of: 'creator'


  has_many :attendee_events, foreign_key: :attendee_id
  has_many :attended_events, through: :attendee_events
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
  end

end

app/controllers/attendee_events_controller.rb
class AttendeeEventsController < ApplicationController

  before_action :authenticate_user!
  before_action :find_event
  before_action :find_events, only: [:new]

  def index
    @attended_events = AttendeeEvent.all
  end

  def new
    @attendee_event = AttendeeEvent.new
  end

  # def show
  #   @attendee_event = AttendeeEvent.find(attendee_event_params)
  # end

  def create
    @attendee_event = @event.attendee_events.build(attendee_id: current_user.id)

    if @attendee_event.save
      redirect_to @event, notice: 'You are now attending this event.'
    else
      render :new
    end
  end

  def destroy
    @attendee_event = @event.attendee_events.find_by(attendee_id: current_user.id)

    if @attendee_event
      @attendee_event.destroy
      redirect_to @event, notice: 'You are no longer attending this event.'
    else
      redirect_to @event, alert: 'You are not attending this event.'
    end
  end


  private
    def find_event
      @event = Event.find(params[:event_id])
    end

    def find_events
      @events = Event.all
    end

    def attendee_event_params
      params.require(:attendee_event).permit(:attended_event_id)
    end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController

before_action :authenticate_user!, only: [:new, :create]

  def index
    @events = Event.all
  end

  def new
    @event = Event.new
  end

  def show
    @event = Event.find(params[:id])
  end


  def create
    @event = current_user.created_events.build(event_params)
    if @event.save
      flash[:success] = "Event was successfully created"
      redirect_to @event
    else
      flash[:error] = "Something went wrong"
      render 'new'
    end
  end

  private
    def event_params
      params.require(:event).permit(:location, :title, :about, :event_date)
    end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/attendee_events_helper.rb
module AttendeeEventsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/attendee_events/index.html.erb
<h2>Attendees</h2>
<ul>
  <% @event.attendees.each do |attendee| %>
    <li><%= attendee.email %></li>
  <% end %>
</ul>

app/views/attendee_events/new.html.erb
<!-- app/views/attendee_events/new.html.erb -->
<div class="form">
  
  <h1>Attend an Event</h1>
  
  <%= form_with(model: @attendee_event, url: attendee_events_path, local: true) do |form| %>
    <div class="field">
      <%= form.label :event_id, "Select Event" %>
      <%= form.collection_select :event_id, @events, :id, :name, prompt: "Choose an event" %>
    </div>
  
    <div class="actions">
      <%= form.submit "Attend" %>
    </div>
  <% end %>
  
  <%= link_to 'Back', events_path %>
</div>

app/views/attendee_events/show.html.erb
<!-- app/views/events/show.html.erb -->

<h1><%= @event.name %></h1>
<p><%= @event.about %></p>

<% if @event.attendees.include?(current_user) %>
  <%= button_to 'Unattend', event_attendee_event_path(@event, @event.attendee_events.find_by(attendee_id: current_user.id)), method: :delete %>
<% else %>
  <%= button_to 'Attend', event_attendee_events_path(@event), method: :post %>
<% end %>

<h2>Attendees</h2>
<ul>
  <% @event.attendees.each do |attendee| %>
    <li><%= attendee.name %></li>
  <% end %>
</ul>

<%= link_to 'Back to Events', events_path %>

app/views/events/index.html.erb
<h1>Community Events</h1>

<ul>
    <% @events.each do |event| %>
        <li>
            <%= link_to "#{event.title}", event %>
        </li>
    <% end %>
</ul>

<%= link_to "Create An Event", new_event_path %>

app/views/events/new.html.erb
<div class="form">
    <h1> New Event </h1>
    <%= form_with model: @event do |form| %>
    
        <div>
            <%= form.label :title %>
            <%= form.text_field :title%>
        </div>
    
        <div>
            <%= form.label :about %>
            <%= form.text_area :about %>
        </div>
    
        <div>
            <%= form.label :location %>
            <%= form.text_field :location%>
        </div>
    
        <div>
            <%= form.label :event_date %>
            <%= form.date_field :event_date%>
        </div>
    
        <div>
            <%= form.submit %>
        </div>
    
    <% end %>
    
    <%= link_to 'Back to Events', events_path %>
    
</div>

app/views/events/show.html.erb
<!-- app/views/events/show.html.erb -->

<% if user_signed_in? %>
  <p>Hello, <%=current_user.username%> </p>

  <h1><%= @event.title %></h1>
  <p>Topic: <%= @event.about %></p>
  <p>Event date: <%= @event.event_date %></p>

  <% if @event.attendees.include?(current_user) %>
    <%= button_to 'Revock Attendance', event_attendee_event_path(@event, @event.attendee_events.find_by(attendee: current_user)), method: :delete %>
  <% else %>
    <%= button_to 'Attend', event_attendee_events_path(@event), method: :post %>
  <% end %>
  
  <h2>Attendees</h2>
  <ul>
    <% @event.attendees.each do |attendee| %>
      <li><%= attendee.username %></li>
    <% end %>
  </ul>
  
  
  
  <h3>Past Events</h3>
  <ul>
    <% current_user.attended_events.where('event_date < ?', Time.now).each do |event| %>
      <li><%= event.title %> - <%= event.event_date.strftime("%B %d, %Y") %></li>
    <% end %>
  </ul>
  
  <h3>Upcoming Events</h3>
  <ul>
    <% current_user.attended_events.where('event_date >= ?', Time.now).each do |event| %>
      <li><%= event.title %> - <%= event.event_date.strftime("%B %d, %Y") %></li>
    <% end %>
  </ul>
  <%= link_to 'Back to Events', events_path %>
<% else %>
  <h1><%= @event.title %></h1>
  <p>Topic: <%= @event.about %></p>
  <p>Event date: <%= @event.event_date %></p>
  <%= link_to 'Back to Events', events_path %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PrivateEvent</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>

    <nav>
      <div class="nav-bar container">
        <% if user_signed_in? %>
            
          <ul class="flex flex_end">
            <li>
              <%= link_to "Events", events_path %>
            </li>
            <li>
              <%= link_to "Create Event", new_event_path %>
            </li>
        
            <li>
              <%= button_to "sign out", destroy_user_session_path, method: "delete" %>
            </li>
          </ul>
        
        <% else %>
          <ul class="flex flex_end">
            <li>
              <%= link_to "Events", events_path %>
            </li>
            <li>
              <%= link_to "Sign up", new_user_registration_path %>
            </li>
            <li>
              <%= link_to "sign in", new_user_session_path %>
            </li>
          </ul>
        <% end %>
      </div>




    </nav>
    
    <%= notice %>
    <%= alert %>
    <div class="container"><%= yield %></div>

  </body>
</html>

app/views/users/attended_events.html.erb
<h2>Event Attendance</h2>
<ul>
  <% current_user.attended_events.each do |attended_event| %>
    <li><%= attended_event.title %></li>
    <li><%= attended_event.about%></li>
    <li><%= attended_event.event_date%>

  <% end %>
</ul>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= button_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), data: { turbo: false } %><br />
  <% end %>
<% end %>